name: Zuri External Tools​ Plugin
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest    
        strategy: 
            matrix:
              node-version: [16.x]
            
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v2

          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node-version }}  
          - name: Install app dependencies
            run: yarn install

          - name: Build app
            run: yarn build --if-present
