name: Zuri External Tools​ Plugin
on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install app dependencies
        run: cd server && yarn install

      - name: Build frontend and backend
        run: cd server && yarn build --if-present

      - name: Start app
        run: cd server && yarn start
